language: go

env:
  global:
    - secure: aBZhGkqGUPQaoc52zxlqH7XpOwRqxtfvT5C0swC9rGmvbhu/wKuOXiFmXY33QymE75vC+t9zl3cxqPq6ViBCAEeOuFlJ+ym1qPw8SSJEd/UeTn4/KeNcMQZTnk2jCxfoFiKybguCm4j2GCtwOuc5b+yRuFrrlER2H9VVWFQESBeQCRadnRmpEyI7jeOnSUlKpB0aIMQw1XWM9j3g+z8RPin72rzJCLe3MAf9RPLUG6HRHFPzoMy8EtKVO5NQRlO0syyVLOj38mJMI12HXuHFs2m4vk7LNCGCxCLIp8HN+Mu0YqHy08ykDbh4JfFFBwZNBtvdtL1OzCJKHM8YM2RcGmQBcNJV0AR5Hoki3Rt+Ba2QWtuH5hKQ8G08L+aDv+1lcoJnsfPK1BgHgkv6/5fnMuu1vAt5cwwp8JsiDKQaifVjPh37HiqwBGF1YS5bzJkiGKlp7ufEAvr39+KXyHWtII+P9Jp5M8jxLagYgRySI5JxslEmzOalp+D94fBa0beqdKvs1OAYwrzIpYMVW4leon4LJ9lNvVB6/e+/X3IdRxz8jE1gHNDSpA6poIZdHQejbLa72dH8V6012zXV8vS8/yaj1gnh6dXm11b2InlTTkehZ1yzLVcad2y62Y/SxCxtjb2Q02SKdcvo4CZzWMLjk0JWfKz27xfB2Mi4mtPoQ3Q=
    - GO111MODULE=on

go:
  - "1.12"
  - "1.13"

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -race -v -covermode=atomic ./...
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
